// Generated by CoffeeScript 2.5.1
(function() {

  /*
  normalize = (input) =>
    if 
      typeof input == 'string'

      if [
        3,
        6,
      ].indexOf (
        input.charAt 0 == '#' ?
        input.slice 1 :
        input
      ).length != -1
        console.log "it is hex"
    else 
      console.log 
  */
  var hexNumConverter, input;

  input = '#4F9AA4';

  input = input.slice(1);

  console.log(`input: ${input}`);

  hexNumConverter = (hexnum) => {
    var range;
    //"0123456789abcdef"
    range = ([0, 1, 2, 3, 4, 5, 6, 7, 8, 9].concat((function() {
      var results = [];
      for (var j = 'a'; 'a' <= 'f' ? j <= 'f' : j >= 'f'; 'a' <= 'f' ? j++ : j--){ results.push(j); }
      return results;
    }).apply(this))).join('');
    return range.indexOf(hexnum);
  };

  console.log(`rgb(${input.match(/.{2}/g).map((point) => {
    var hexNum, i, results;
//parseInt(point)
//.toString(10)
    results = [];
    for (i in point) {
      hexNum = point[i];
      results.push(Math.pow(16, (point.length - i - 1) * hexNumConverter(hexNum)));
    }
    return results;
  }).map((point) => {
    return point.join('');
  }).join(',')}`);

}).call(this);
